- name: install mariadb package (OracleLinux)
  tags: oraclelinux,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "OracleLinux"

- name: install mariadb package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

